# GNU Lesser General Public License v3.0 only
# Copyright (C) 2020 Artefact
# licence-information@artefact.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
ENV: example
K8S:
  CLUSTER_NAME: sftp-gateway
  REGION: europe-west1
  ADMINUSERACCOUNT: admin@example.com
  MANAGED_CLOUD: GKE  # or AKS, EKS, ACS
APP:
  SERVICE_IP: 0.0.0.0  # Replace this with the generated IPv4 for your Kubernetes service
  DOCKER_REGISTRY: docker.io  # Do not change if you are just modifying this file
  DOCKER_URL: nautilus-sftp-gateway:latest  # Do not change if you are just modifying this file
  NAME: nautilus-sftp-example
  SERVICE_PORT: 22
  HOST_PORT: 3000
  SERVICE_INTERNAL: false
  PERSIST_FILES: false
USERS:
  <SFTP_USERNAME>:
    GCP_PROJECTS:
      <PROJECT_ID>:
        BUCKETS:
          <BUCKET_ID>:
            INCLUDE: "*"
            EXCLUDE: null
          <OTHER_BUCKET_ID>:
            INCLUDE: "*"
            EXCLUDE: null
    AWS_ACCOUNTS:
      <ACCOUNT_ID>:
        BUCKETS:
          <BUCKET_ID>:
            INCLUDE: "*"
            EXCLUDE: null
